services:
  - type: web
    name: abd-portfolio
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHON_VERSION
        value: "3.12.2"
