# Generated by Django 5.1.3 on 2026-05-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, help_text='Short caption', max_length=200)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('level', models.CharField(choices=[('international', 'International'), ('national', 'National'), ('school', 'School'), ('regional', 'Regional')], default='national', max_length=20)),
                ('icon', models.CharField(default='🏆', help_text='Emoji icon', max_length=10)),
                ('featured', models.BooleanField(default=True, help_text='Show on main page grid')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Awards & Achievements',
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('country_code', models.CharField(help_text='2-letter ISO code (PK, SG, CA)', max_length=4)),
                ('is_homeland', models.BooleanField(default=False, help_text='Pakistan gets the green stamp.')),
                ('order', models.IntegerField(default=0)),
                ('chapter_title', models.CharField(blank=True, max_length=120)),
                ('chapter_body', models.TextField(blank=True, help_text='Markdown supported.')),
                ('map_x_pct', models.FloatField(default=50, help_text='Position % from left on the map.')),
                ('map_y_pct', models.FloatField(default=50, help_text='Position % from top on the map.')),
            ],
            options={
                'verbose_name_plural': 'Cities (Journey)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Messages (Inbox)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if current.', null=True)),
                ('description', models.TextField(help_text='Markdown supported.')),
                ('f1_position', models.PositiveSmallIntegerField(help_text='P1 = current/most recent, P2 = next, etc.', unique=True)),
                ('track_x_pct', models.FloatField(default=50, help_text='Position on track SVG, % from left.')),
                ('track_y_pct', models.FloatField(default=50, help_text='Position on track SVG, % from top.')),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['f1_position'],
            },
        ),
        migrations.CreateModel(
            name='F1Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('number', models.PositiveSmallIntegerField()),
                ('team', models.CharField(choices=[('ferrari', 'Ferrari'), ('mercedes', 'Mercedes'), ('redbull', 'Red Bull'), ('mclaren', 'McLaren'), ('aston', 'Aston Martin'), ('williams', 'Williams'), ('alpine', 'Alpine'), ('sauber', 'Sauber'), ('haas', 'Haas'), ('rb', 'RB')], max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'F1 Drivers (Beyond Code)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MovieFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('director', models.CharField(blank=True, max_length=120)),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Out of 5')),
                ('order', models.IntegerField(default=0)),
                ('poster_gradient', models.CharField(default='tdk', help_text='CSS gradient key: tdk, intst, dep, incep', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Movies (Beyond Code)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Passion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Other Passions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Syed Abdullah Ahmed', max_length=120)),
                ('short_name', models.CharField(default='Abdullah', max_length=60)),
                ('tagline', models.CharField(default='Software Engineer · Cricketer · Builder', max_length=200)),
                ('bio_short', models.TextField(blank=True, help_text='Used in the hero section. Markdown supported.')),
                ('bio_long', models.TextField(blank=True, help_text='Used in the About Me section. Markdown supported.')),
                ('pull_quote', models.CharField(blank=True, help_text='The big italic pull-quote in About Me.', max_length=300)),
                ('headshot', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('polaroid_photo', models.ImageField(blank=True, help_text='The polaroid photo on the About page.', null=True, upload_to='profile/')),
                ('polaroid_caption', models.CharField(blank=True, default='where it all began ✦', max_length=120)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('location', models.CharField(default='Toronto, Canada', max_length=120)),
                ('verse_arabic', models.CharField(blank=True, max_length=300)),
                ('verse_translation', models.CharField(blank=True, max_length=300)),
                ('verse_reference', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('language', 'Language'), ('framework', 'Framework / Library'), ('tool', 'Tool / Ops')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome class (optional)', max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Tech / Skills',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('subtitle', models.CharField(blank=True, help_text='Italic tagline', max_length=200)),
                ('description', models.TextField(help_text='Short prose description. Markdown supported.')),
                ('detail', models.TextField(blank=True, help_text='Long-form case study on detail page. Markdown supported.')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('demo_url', models.URLField(blank=True, help_text='YouTube / video / live demo URL')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('category', models.CharField(choices=[('full-stack', 'Full-Stack'), ('backend', 'Backend / API'), ('ai', 'AI / Python'), ('frontend', 'Frontend'), ('mobile', 'Mobile'), ('other', 'Other')], default='full-stack', max_length=20)),
                ('status', models.CharField(choices=[('shipped', 'Shipped'), ('in_progress', 'In Progress'), ('archived', 'Archived')], default='shipped', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('shipped_date', models.DateField(help_text='Used for the release log timestamp')),
                ('order', models.IntegerField(default=0, help_text='Lower = higher in the list')),
                ('tech_stack', models.ManyToManyField(blank=True, related_name='projects', to='core.tech')),
            ],
            options={
                'ordering': ['order', '-shipped_date'],
            },
        ),
    ]
