# Generated by Django 5.1.3 on 2026-06-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='highlights',
            field=models.TextField(blank=True, help_text='Technical highlights — one bullet per line. Shown as a list in the project card.'),
        ),
    ]
