# Generated by Django 5.1.3 on 2026-06-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='promo_video',
            field=models.FileField(blank=True, help_text='Short AD-style promo (mp4). Shown in the project card slot.', null=True, upload_to='projects/videos/'),
        ),
    ]
