# Generated by Django 5.1.3 on 2026-06-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_promo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='period',
            field=models.CharField(choices=[('highschool', 'High School'), ('university', 'University'), ('beyond', 'Beyond')], default='university', help_text='Which trophy cabinet this sits in.', max_length=20),
        ),
    ]
